### ISSUE TITLE
[FEAT/FS002B/ash] 스케줄 편성 결과 시각화 화면 개발

### ISSUE THREAD

**Issue by sohyun-ahn** [POSTCO2024/frontend#12]
## 💡 Feature Issue
- **이슈 제목**: 스케줄 편성 결과 시각화 화면 개발
- **요약**: 스케줄 확정 전 막대그래프로 임시 스케줄 편성된 리스트를 보여주고, drag&drop으로 변경 가능하게 시각화
- **기능 설명**: 막대그래프로 폭, 두께, 온도 를 표시하고, drag&drop 가능한 막대그래프 구현 
- **배경 및 맥락**: 롤편성이 된 후 스케줄 확정되기 전 스케줄이 편성된 리스트들을 막대그래프 형태로 시각화한다. 유저는 이를 보고 막대그래프를 drag&drop으로 수정할 수 있어야 하고, 확정 버튼을 누르면 스케줄이 확정된다.

## 🌿  To-do

- [ ] 폭 그래프
- [ ] 두께그래프
- [ ] 온도 그래프
- [ ] 막대그래프들 drag&drop 가능하게
- [ ] 하나 선택시 세부사항 뜨는 모달창 구현
- [ ] 막대그래프들을 원래 상태로 되돌리는 초기화 버튼 구현
- [ ] 스케줄 확정 버튼 구현
- [ ] Tab으로 그래프와 리스트 분리
- [ ] select로 공정별 조회 구현
- [ ] 롤 단위 번호 text로 표시되게 구현

## 📅 Timeline
- **시작일**: 2024-08-07
- **종료일**: 2024-08-11
- **마일스톤 이름**: 스케줄링 시각화 화면 개발
    - **목표**: drag&drop 가능한 막대 그래프 구현
    - **기한**: 2024-08-16
    - **관련 이슈**: #9, #11

## 🧩 Dependencies

- [ ] #11 공통 컴포넌트 - Tab, Table, Button, SearchBar, Dropdown
- [ ] #9 공통 컴포넌트 - Modal

## 👥 Assignees & Reviewers
- **할당자**: @sohyun-ahn 
- **리뷰어**: @yerimee82 

## 📌 Notes

- **참고 사항**: 시각화 라이브러리 이용 예정
