### ISSUE TITLE
[FEAT/FS001A1/ash] 스케줄편성 모달창

### ISSUE THREAD

**Issue by sohyun-ahn** [POSTCO2024/frontend#9]
## 💡 Feature Issue
- **이슈 제목**: 스케줄편성 모달창
- **요약**: 스케줄편성이 완료되었다는 모달창입니다.
- **기능 설명**: 스케줄 편성 버튼을 클릭하게 되면 편성이 완료되었다는 알림창으로 사용합니다.
- **배경 및 맥락**: before - 스케줄편성전 작업대상재리스트가 떠있는 화면에서 롤편성하기 버튼 클릭, now - 현재 모달창, after - 스케줄결과화면에서 편성 결과를 확인하는 화면으로 전환

## 🌿  To-do
- [x] 확인 버튼
- [x] 체크 이미지 삽입
- [x] 롤편성이 완료되었다는 메시지 내용

## 📅 Timeline
- **시작일**: 2024-08-07
- **종료일**: 2024-08-07
- **마일스톤 이름**: 스케줄 편성 모달창 개발
    - **목표**: 공통 컴포넌트 모달창 개발 및 스케줄 편성 모달창 개발
    - **기한**: 2024-08-07
    - **관련 이슈**: 

## 🧩 Dependencies
- [x] <예정> [FEAT/FS001A/000] 스케줄 편성 화면

## 👥 Assignees & Reviewers
- **할당자**: @sohyun-ahn 
- **리뷰어**: @yerimee82 

## 📌 Notes
- **참고 사항**: Dependencies의 화면은 아직 생성되지 않았습니다.
